### ISSUE TITLE
5Hz support

### ISSUE THREAD

**Issue by egasvegas1109** [GANESH-ICMC/esp32-deauther#21]
Does it work for 5Hz?

**Comment by SkepticSeptic** [comment]
I assume you mean 5 GHz, in which case odds are no. The ESP32 board only supports 2.4GHz due to the WiFi chip it uses. For attempting to deauth 5GHz and possibly 6GHz networks, you will need to use a computer supporting these, along with a network card capable of monitoring mode + packet injection. For more info you can refer to SpaceHuhn's great documentation on the topic: https://blog.spacehuhn.com/5ghz-deauther?x-host=blog.spacehuhn.com
